# Tensor

In [14]:
x = torch.randn([32,3,256,256])

Formula for output size for Convolutions:
$[(W−K+2P)/S]+1$

## cat vs stack

In [10]:
import torch

In [11]:
a = torch.Tensor([1])
b = torch.Tensor([2])
torch.cat([a,b], dim=0)

tensor([1., 2.])

In [12]:
torch.stack([a,b], dim=0)

tensor([[1.],
        [2.]])

In [13]:
torch.stack([a,b], dim=1)

tensor([[1., 2.]])